#!/bin/bash

echo "🚀 GitHub Setup Fix"
echo "=================="
echo ""
echo "1. First, create the GitHub repository:"
echo "   - Go to https://github.com"
echo "   - Click '+' → 'New repository'"
echo "   - Name: ai-interview-platform"
echo "   - Make it Public"
echo "   - Don't initialize with README"
echo "   - Click 'Create repository'"
echo ""
echo "2. After creating the repository, GitHub will show you the correct URL"
echo "   It will look like: https://github.com/YOUR_USERNAME/ai-interview-platform.git"
echo ""
echo "3. Replace YOUR_USERNAME with your actual GitHub username and run:"
echo ""
echo "   git remote set-url origin https://github.com/YOUR_ACTUAL_USERNAME/ai-interview-platform.git"
echo "   git push -u origin main"
echo ""
echo "4. If you need to remove the current remote first:"
echo "   git remote remove origin"
echo "   git remote add origin https://github.com/YOUR_ACTUAL_USERNAME/ai-interview-platform.git"
echo "   git push -u origin main"
echo ""
echo "✅ Your repository is ready to push!"


